name: flutter_stack_card_plus
description: 一个层叠式可拖动的卡片组件
version: 0.0.1
homepage: https://github.com/yuxiaochao/flutter_stack_card_plus

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_slider_indicator: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

